name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            # Navigate or create app folder
            mkdir -p ~/nextjs-app
            cd ~/nextjs-app

            # Pull latest code
            if [ ! -d ".git" ]; then
              git clone git@github.com:${GITHUB_REPOSITORY}.git .
            else
              git pull origin main
            fi

            # Create env file
            echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" > .env

            # Build & run docker
            docker build -t nextjs-app .
            docker rm -f nextjs-app || true
            docker run -d --name nextjs-app -p 3000:3000 --env-file .env nextjs-app
