name: Deploy Next.js App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.EC2_KEY }}

      - name: Copy files to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "mkdir -p ~/nextjs-app"
          rsync -avz --exclude '.git' ./ ubuntu@${{ secrets.EC2_HOST }}:~/nextjs-app/

      - name: Build & Run Docker Container on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@${{ secrets.EC2_HOST }} "
            cd ~/nextjs-app &&
            docker build -t nextjs-app . &&
            docker stop nextjs-app || true &&
            docker rm nextjs-app || true &&
            docker run -d --name nextjs-app \
              -p 3000:3000 \
              -e NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
              nextjs-app
          "
